import cover1 from "../assets/cover1.jpg";
import cover2 from "../assets/cover2.jpg";

const stories = [
  {
    id: 1,
    title: "Hoá Ra Ta Đã Vô Địch Từ Lâu",
    author: "Đang Cập Nhật",
    status: "Đang Cập Nhật",
    views: 1000,
    genres: ["Drama", "Fantasy", "Manhua", "Xuyên Không", "Truyện Màu"],
    cover: cover1,
    lastestChapter: 313,
    time: "15 giờ trước",
    hot: true,
    description: "Một thanh niên vô tình phát hiện mình đã vô địch từ lâu mà không hề hay biết.",
  },
  {
    id: 2,
    title: "Gậy Gỗ Cấp 99+",
    author: "Đang Cập Nhật",
    status: "Đang Cập Nhật",
    views: 9999,
    genres: ["Action", "Comedy", "Manhwa", "Magic", "Truyện Màu"],
    cover: cover2,
    lastestChapter: 100,
    time: "1 giờ trước",
    hot: true,
    description: "Câu chuyện về một nhân vật sở hữu cây gậy gỗ cấp 99+ vượt mọi thử thách.",
  },
  {
    id: 3,
    title: "Hoá Ra Ta Đã Vô Địch Từ Lâu",
    author: "Đang Cập Nhật",
    status: "Đang Cập Nhật",
    views: 1000,
    genres: ["Drama", "Fantasy", "Manhua", "Xuyên Không", "Truyện Màu"],
    cover: cover1,
    lastestChapter: 313,
    time: "15 giờ trước",
    hot: true,
    description: "Một thanh niên vô tình phát hiện mình đã vô địch từ lâu mà không hề hay biết.",
  },
  {
    id: 4,
    title: "Gậy Gỗ Cấp 99+",
    author: "Đang Cập Nhật",
    status: "Đang Cập Nhật",
    views: 9999,
    genres: ["Action", "Comedy", "Manhwa", "Magic", "Truyện Màu"],
    cover: cover2,
    lastestChapter: 100,
    time: "1 giờ trước",
    hot: true,
    description: "Câu chuyện về một nhân vật sở hữu cây gậy gỗ cấp 99+ vượt mọi thử thách.",
  },
  {
    id: 5,
    title: "Gậy Gỗ Cấp 99+",
    author: "Đang Cập Nhật",
    status: "Đang Cập Nhật",
    views: 9999,
    genres: ["Action", "Comedy", "Manhwa", "Magic", "Truyện Màu"],
    cover: cover2,
    lastestChapter: 100,
    time: "1 giờ trước",
    hot: true,
    description: "Câu chuyện về một nhân vật sở hữu cây gậy gỗ cấp 99+ vượt mọi thử thách.",
  },
  {
    id: 6,
    title: "Hoá Ra Ta Đã Vô Địch Từ Lâu",
    author: "Đang Cập Nhật",
    status: "Đang Cập Nhật",
    views: 1000,
    genres: ["Drama", "Fantasy", "Manhua", "Xuyên Không", "Truyện Màu"],
    cover: cover1,
    lastestChapter: 313,
    time: "15 giờ trước",
    hot: true,
    description: "Một thanh niên vô tình phát hiện mình đã vô địch từ lâu mà không hề hay biết.",
  },
  {
    id: 7,
    title: "Gậy Gỗ Cấp 99+",
    author: "Đang Cập Nhật",
    status: "Đang Cập Nhật",
    views: 9999,
    genres: ["Action", "Comedy", "Manhwa", "Magic", "Truyện Màu"],
    cover: cover2,
    lastestChapter: 100,
    time: "1 giờ trước",
    hot: true,
    description: "Câu chuyện về một nhân vật sở hữu cây gậy gỗ cấp 99+ vượt mọi thử thách.",
  },
  {
    id: 8,
    title: "Hoá Ra Ta Đã Vô Địch Từ Lâu",
    author: "Đang Cập Nhật",
    status: "Đang Cập Nhật",
    views: 1000,
    genres: ["Drama", "Fantasy", "Manhua", "Xuyên Không", "Truyện Màu"],
    cover: cover1,
    lastestChapter: 313,
    time: "15 giờ trước",
    hot: true,
    description: "Một thanh niên vô tình phát hiện mình đã vô địch từ lâu mà không hề hay biết.",
  },
  {
    id: 9,
    title: "Gậy Gỗ Cấp 99+",
    author: "Đang Cập Nhật",
    status: "Đang Cập Nhật",
    views: 9999,
    genres: ["Action", "Comedy", "Manhwa", "Magic", "Truyện Màu"],
    cover: cover2,
    lastestChapter: 100,
    time: "1 giờ trước",
    hot: true,
    description: "Câu chuyện về một nhân vật sở hữu cây gậy gỗ cấp 99+ vượt mọi thử thách.",
  },
];

export default stories;
